apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authentification-service.fullname" . }}
  labels:
    {{- include "authentification-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "authentification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "authentification-service.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "authentification-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.port_key }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.db_username_key }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.db_password_key }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.db_host_key }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.db_name_key }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.jwt_secret_key }}
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.jwt_expiration_key }}
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.keycloak_realm_key }}
            - name: KEYCLOAK_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.keycloak_server_url_key }}
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.keycloak_client_id_key }}
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.keycloak_client_secret_key }}
            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.keycloak_admin_username_key }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.keycloak_admin_password_key }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
